[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/polyglot'

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  source ~/.config/nvim/plugins/vim-indent-guides.vim
'''
